### PR TITLE
Changed to FitX API

### PR DESCRIPTION
**Pull request by JayReturns**
According to #5 I integrated the FItX API into this integration.

### CODE REVIEW

**Comment by Raukze** [comment]
Thanks for the contribution. It looks pretty promising. I'll take a look at it and will report back to you 😊

**Comment by Raukze** [comment]
Well done and it works like a charm!

A couple of things I would like to have changed before I will merge.
My thought is to have a CSV-list of all location + their `id` in my repo that gets updated regularly via [this script](https://gist.github.com/Raukze/75641934b95e62e6540e5de10cdc1d49) (rewritten from your gist). Then we wouldn't need the `id` which used to be sth. like `bielefeld-mitte` and I would like the `num_id` parameter (which you introduced) to be "renamed" to `id` and have that be the only required parameter in the config. This would mean a breaking change but I think it's the right option.
Then, when someone wants to configure a sensor, they only need to open the list and search for the `id` themselves.

@JayReturns What's your opinion on that?

**Comment by JayReturns** [comment]
That sounds like the best alternative. I wasn't too happy about the `num_id` either because it introduces a sort of redundancy.

**Comment by Raukze** [comment]
Hi @JayReturns, you probably saw that I mentioned you in #9. Are you interested in maintaining this repo? I gave you the permission to participate on this repo. Also I have tested with some changes a couple of weeks ago which I just pushed into the dev branch. It'd be great if you could implement these changes https://github.com/Raukze/home-assistant-fitx/pull/7#issuecomment-1347919488.

**Comment by JayReturns** [comment]
Hi @Raukze. Thank you for the invitation. As mentioned in the ongoing issue I'm using a restful sensor now which makes this repository obsolete. I could post the code in this repo but I don't think it's necessary to maintain this repo at all.

**Pull request merged**
